### ISSUE TITLE
New API with less parameters

### ISSUE THREAD

**Issue by amirouche** [paulgirard/pygexf#17]
The current API requires a lot of method parameters (`Gexf` constructor, `Gexf.addNode`, `Gexf.addEdge`) my proposition is to separate **required** parameters which will still be set via parameters and **optional** parameters which will be set by setting properties.

I understand that this is a rather cosmetic change. Also I'd like to deprecate old methods to superseed them with `pep8_compliant_method_names`. This will make, I hope, the library more easier to the mind.

**Comment by paulgirard** [comment]
About **required** and **optional** parameters, I think some actual required parameter might be set as optionnal with a default value (lot in Graph constructor and the label in addNode).
I would let the optionnal parameters where they are not to break the API.

When you say "by setting properties" you mean by "setting attributes" of the object ?
If yes, you can already do it if you prefer.

pep8 compliance isn't an important goal to me.
I would like it better in pep8 mode but I have to keep that for the next big refacto to break everything.

**Comment by amirouche** [comment]
> About required and optional parameters, I think some actual required parameter might be set as optionnal with a default value (lot in Graph constructor and the label in addNode).
> I would let the optionnal parameters where they are not to break the API.

There is not need to break the API; the old API can work with the new API. I probably need to document precisely what I aiming at. 

> When you say "by setting properties" you mean by "setting attributes" of the object ?

Yes, but it's not always the best solution either, since some properties are contrained like mode & type.

> pep8 compliance isn't an important goal to me.

This is not only pep8 compliance. Having smaller argument counts and defer optional fields to "later" allow a smoother learning curve.

**Comment by amirouche** [comment]
Personal backlog clean-up.
