### ISSUE TITLE
Take advantage of “lxml custom Element classes” (or objectify) ?

### ISSUE THREAD

**Issue by amirouche** [paulgirard/pygexf#18]
With the current inner working the gexf file is present two times in memory, one time as a gexf class objects another time as `lxml.etree.Element`. This can be a performance problem for both import and export.

I think that with [lxml custom Element classes](http://lxml.de/element_classes.html) we can improve the situation. What do you think? Are you interested in this change?

**Comment by paulgirard** [comment]
That looks pretty interesting. Never had a memory footprint issue so far though.
Not a top priority but might a nicer implementation indeed.
Again here you are more likely targeting a big refacto.

Are you interested into building a new version of pygexf ?

**Comment by amirouche** [comment]
> That looks pretty interesting. Never had a memory footprint issue so far though.

That's what I figured out. "you" people have lots and lots of RAM :racehorse: 

> Not a top priority but might a nicer implementation indeed.

That what I think too.

> Are you interested into building a new version of pygexf ?

Yes, kind of. I don't know how to proceed. I prefer to start with `pygexf` code pedagogical purpose, I already know a lot about writing code from scratch. Anyway, I'll continue to work on my branch. 

I think it would be best to do incremental changes.

**Comment by amirouche** [comment]
Backlog cleanup.
